//
//  MM4Force+Electrostatic.swift
//
//
//  Created by Philip Turner on 10/14/23.
//

// Electrostatic force, using an interaction group to mask out neutral atoms
class MM4ElectrostaticForce: MM4Force {
  
}

// Create a counterforce at short range that corrects for 1/2 of a
// dipole falling on the 1-3 border. In the paper about fluorine, Allinger
// mentioned some 1-4 fluorines on fluoroethane having a repulsive effect
// from their dipoles. This suggests 1-4 interactions ("sclfac = 1.000") are
// included, but perhaps not the 1-3 interactions.
//
// Create a different force to handle the dipole-dipole interactions along
// every possible path between two bonds, which wasn't fully handled when
// recording the 1-3/1-4 nonbonded exceptions. In other words, enumerate every
// torsion out there and create a nonbonded exception force for it.
//
// Find all the bonds on atom 1 that are present in a torsion. Repeat the same
// process for atom 4. Then, compute an O(n^2) algorithm on all of the dipole
// permutations ('n' in number of dipoles, often n = 2-3). A final force
// computes a charge-charge interaction with the partial charge generated by
// the involved bonds omitted.
class MM4ElectrostaticExceptionForce {
  
}
